### ISSUE TITLE
White Background on dark syntax

### ISSUE THREAD

**Issue by sobrecarga** [Alchiadus/base16-syntax#10]
Even when you select dark theme, background for empty editor, active bar, and active scrollbar is white.

![bug](https://cloud.githubusercontent.com/assets/11811348/8241443/c004346c-15df-11e5-9056-c9c751a3cefa.png)

**Comment by marshallbu** [comment]
I had a similar issue (https://github.com/atom/one-dark-ui/issues/78), where certain themes are expecting to see a `styles/syntax-variables.less` file to color things, like the tabs.  

![screen shot 2015-06-09 at 12 39 41 pm](https://cloud.githubusercontent.com/assets/607054/8067778/bdd4dec2-0ea4-11e5-97fc-acde135774ef.png)

My temp fix was to add the file manually to add the file, and then throw the following inside:
```
@syntax-background-color: #111;
```

So that for my needs, the One Dark UI theme would properly color the tab background.

**Comment by Alchiadus** [comment]
Apologies, I somehow missed the notification for the original issue. As you pointed out in the [other issue](https://github.com/atom/one-dark-ui/issues/78), a `styles/syntax-variables-{light/dark}.less` file is being used instead, depending on which variant the user selects. It did not occur to me that the variables that go inside the `styles/syntax-variables.less` file would not be read properly by other packages if the exact file name is not used.

It should be possible to merge the two files and use a variable inside `styles/syntax-variables.less` to control the colors instead of having two separate files. I'll try to fix this soonish, but I may not have time until late next week.

**Comment by marshallbu** [comment]
No worries my friend, thanks for the quick response!

**Comment by flannelhead** [comment]
I wonder if it's due to this same issue, but also the cursor color seems to be off (too dark to see) when using the dark variant.

**Comment by Alchiadus** [comment]
@flannelhead which dark theme are you using? The background color is defined by `base00` and the cursor color is defined by `base05`. I (quickly) went over all the different themes and the contrast between `base00` and `base05` appears to be high in all cases. I mainly use the Eighties theme, for me it looks like this:
![base16-eighties-dark-cursor](https://cloud.githubusercontent.com/assets/576095/8430024/75a45e5e-1f2d-11e5-8031-b7e74cbeb3c5.png)

**Comment by flannelhead** [comment]
Oops, sorry. I forgot to mention I'm using vim-mode. In the normal mode, the cursor is a block instead of a vertical line. It looks like this:
![cursorcolour](https://cloud.githubusercontent.com/assets/5001906/8431408/f27c5058-1f41-11e5-9662-e86a213d5f0a.png)
Perhaps there's some other CSS attribute to set for the cursor besides border-color? (I've not investigated this.) So this is likely another issue. Sorry for the noise. Should I open a new ticket for this?

FWIW, I'm using the Flat dark theme. The UI theme is One Dark.

**Comment by Alchiadus** [comment]
> Should I open a new ticket for this?

Yes please, it'll be easier if we can keep the issues separate. I'll take a look at it there, I'm not yet familiar with how vim-mode colors the cursor.
