### ISSUE TITLE
Faint cursor colour in vim-mode's command mode

### ISSUE THREAD

**Issue by flannelhead** [Alchiadus/base16-syntax#12]
Using Base16 Flat dark syntax with vim-mode enabled, the block cursor shown in the command mode is almost too faint to be distinguished from the background.
![cursorcolour](https://cloud.githubusercontent.com/assets/5001906/8439676/3df629e4-1f76-11e5-91b4-dfec9cd5b085.png)
This [vim-mode issue](https://github.com/atom/vim-mode/issues/201) seems relevant, and many have ended up adding a small fix into their stylesheet. The question is, however, is it really worth it fixing in each syntax package separately.

**Comment by Alchiadus** [comment]
Just wanted to give an update and say I definitely haven't forgotten about this. Your [intuition](https://github.com/Alchiadus/base16-syntax/issues/10#issuecomment-117037647) is indeed completely correct, this issue is directly related to #10. Manually fixing that issue by creating the `styles/syntax-variables.less` file with the correct colors filled in for the desired style yields the following result with `vim-mode` enabled when the block cursor is shown in command mode:
![base16-syntax-vim-mode-block-cursor](https://cloud.githubusercontent.com/assets/576095/8633705/2a770f1e-27d7-11e5-9e67-fd4a472084d0.png)

Since `vim-mode` uses the `@syntax-cursor-color` variable and plays with the `opacity` property for the block cursor I don't think any further changes are necessary. If the normal cursor is properly distinguishable then so should the block-cursor be.

The problem right now is that due to a missing `styles/syntax-variables.less` file `vim-mode` cannot find a `@syntax-cursor-color` and thus falls back to a default value, which makes it hard to see for most of the base16 styles.
