### ISSUE TITLE
oceanicnext scheme error

### ISSUE THREAD

**Issue by mjrev** [Alchiadus/base16-syntax#19]
when i try to set oceanicnext scheme, i get stack of errors, first of them is
```
Error compiling Less stylesheet: /home/mjrev/.atom/packages/base16-syntax/index.less
Line number: 2
'schemes/oceanicNext.less' wasn't found
```
original file is named `oceanicnext.less` (lowercase n).
renaming file fixes the problem, but i don't know how would be better by default - changing name of file in schemes folder or in `base16-settings.coffee` file - it's up to you

**Comment by Alchiadus** [comment]
Thank you for reporting this. It's due to a bad assumption on my part in the normalization method. With the addition of the new schemes it is no longer the case that capital letters only occur at word boundaries. I'm on a case insensitive system so I didn't catch it beforehand, a fix should be out shortly.
