### ISSUE TITLE
Ocean Dark JavaScript variables are red

### ISSUE THREAD

**Issue by sotojuan** [Alchiadus/base16-syntax#21]
This is mostly a personal preference, but in my opinion variables should not be red or any colors that "pop up", like red. This is the case in Ocean Dark.

I think one of the white-ish colors would be better, though it'd have to be differentiable from the equals sign (maybe?).

Let me know what you think, I can do a PR if you want!

`@base16-color-base06` looks good to me:

<img width="530" alt="screen shot 2016-03-30 at 3 42 18 pm" src="https://cloud.githubusercontent.com/assets/8217766/14155060/031744f8-f68e-11e5-966c-89f51e4350bd.png">

**Comment by Alchiadus** [comment]
My apologies for the extremely slow response, I've had a few busy weeks.

I agree the variable colors 'pop up', but I am reluctant to change this.

In base16 themes for other editors (e.g. vim, Sublime Text) `base08` (a red color in almost every base16 style) is also used for variables. Someone who has been using a certain theme for a while will expect certain language constructs to be colored in a certain way. I think it's best if there are no (large) differences between highlighting when people move between editors, but use the same syntax scheme. There is also the case where someone simply likes the fact that variables pop up, so they can easily keep track of them.

That said, it doesn't mean that I think using for example `base06` for variable coloring is necessarily a bad idea. I can see the appeal, as it would make most source code look a lot less 'aggressive'. I'm just not sure how we could move forward with this. I don't think changing defaults is a good idea, for the reasons mentioned above. I'm not opposed to offer customization, where users can define their own preferences for certain language constructs. Sadly this will not be easy to achieve in Atom, because customization within syntax themes is not really supported; I already had to use some dirty hacks to allow for picking different styles. There is also the risk that allowing for such customization quickly becomes offering a complete graphical syntax theme builder. One person might like to change the variable color, another might like to change the method color, etc. In your example, changing the variable color from a red-ish color to a grey-ish color would almost automatically imply the constant color would need to be changed from an orange-ish color to perhaps a grey-ish color as well.

As always, I'm open to ideas, suggestions and opinions!
